modLoader = "javafml" #mandatory
loaderVersion = "[4,)" #mandatory
license = "MIT License"
authors = "Pedro Souza" #optional

[[mods]]
modId = "mlib"
version = "${version}"
displayName = "mlib"

[[dependencies.mlib]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mlib]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.215,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mlib]]
modId = "gooeylibs_api"
type = "required"
versionRange = "[3.1.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mlib]]
modId = "adventure_platform_neoforge"
type = "required"
versionRange = "[6.0.0,)"
ordering = "NONE"
side = "BOTH"
